name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: |
        tag=$(date +%s)
        image_repo=srijanlabs/continua-demo
        docker build . --file Dockerfile --tag $image_repo:$tag
        docker tag srijanlabs/continua-demo:$tag $image_repo:latest
    - name: Push image to the Registry
      run: |
        docker push $image_repo:$tag
        docker push $image_repo:latest
