name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TOKEN }}
        tag=$(date +%s)
        image_repo=srijanlabs/continua-demo
        docker build . --file Dockerfile --tag $image_repo:$tag
        docker tag srijanlabs/continua-demo:$tag $image_repo:latest
        docker push $image_repo:$tag
        docker push $image_repo:latest
